version: '3'
services:
  redis:
    image: redis:3.2.3
    container_name: test-redis
    environment:
      - REDIS_PASSWORD="123456"
    restart: always
    volumes:
      - d://docker/redis/data:/data
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.7.22
    container_name: test-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=kfh123456
    ports:
      - "3306:3306"