FROM java:8-jre
MAINTAINER qiudaoyu <5459514@qq.com>

ADD ./jar/grocery-zuul.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=jx-gateway", "-Dpinpoint.applicationName=GATEWAY", "-jar", "/app/grocery-zuul.jar"]

EXPOSE 9999