FROM java:8-jre
MAINTAINER qiudaoyu <5459514@qq.com>

ADD ./jar/grocery-auth.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=grocery-auth", "-Dpinpoint.applicationName=AUTH", "-jar", "/app/grocery-auth.jar"]
