version: '2'
services:
  grocery-eureka:
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    restart: always
    ports:
      - 1025:1025

  grocery-config:
    links:
      - grocery-eureka:eureka
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always

  grocery-zuul:
    links:
      - grocery-eureka:eureka
      - grocery-auth:auth
    build:
      context: ./
      dockerfile: Dockerfile-zuul
    restart: always
    ports:
      - 9999:9999

  grocery-auth:
    links:
      - grocery-eureka:eureka
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    ports:
      - 3000:3000