FROM java:8-jre
MAINTAINER Jx <richard_wai@163.com>

ADD ./jar/jx-auth.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=jx-auth", "-Dpinpoint.applicationName=AUTH", "-jar", "/app/jx-auth.jar"]
