server:
  port: 5002

zipkin:
  collector:
    rabbitmq:
      addresses: 47.93.44.246:5672
      password: 123456
      username: grocery
      virtual-host: grocery_vhost
      queue: zipkin
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      hosts: 47.93.44.246:9200
      cluster: my-search
      index: zipkin
      max-requests: 64
      index-shards: 5
      index-replicas: 1