server:
  port: 4060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: jiangxue
    password: jx123456
    url: jdbc:mysql://47.97.195.85:3306/jiangxue?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 127.0.0.1:2181
      namespace: jx-daemon