jasypt:
  encryptor:
    password: jiangxue
server:
  port: 4000
  context-path: /upms-api
  domain: edu-jx.cn
https:
  port: 8443
  ssl:
    #ssl认证文件的结对路径
    key-store: D:/jiangxue/jiangxue/jx-modules/jx-upms-service/src/main/resources/www.edu-jx.cn.jks
    key-store-password: wo201228
    key-store-type: JKS
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600
swagger:
  enable: false

# sleuth配置
spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ENC(pEp2T842LXZ/LiorB7hVl0r/OCZVN3jLgmSAuXnPKVq3VB6f2K5fGQFQMrFiJVhAM7u1taeBedyO1o+jmJWrKeixp83pAYqREiDZHkwLWM2GkoRv+byDpSeyWAAfTCO/78LwqMl0RsBo6l5XApOaRohaelRKjjRiJtY6Xji7wZwjK9XCxWcy2hlNOe++vxEJ)
    username: ENC(eknZlI1bCNqACsVcpyb8LtA5TMFBITMV)
    password: ENC(ARqbrcb59fay7k5bPtjlGhSNHAWoV6Zb)

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.ribuluo.admin.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
pagehelper:
  helperDialect: mysql
fdfs:
  file-host: http://127.0.0.1:22121/
  tracker-list:
    - 127.0.0.1:22122

task:
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 10
      keepAliveSeconds: 100
      queueCapacity: 300
# 七牛OSS 配置
# qiniu:
#  accessKey: hM2cBDEM0FTYzpXbigRW90kV12NhhzhFM3jCzurJ
#  secretKey: ENC(HM/K0KmtFoZSBhGDEA0Ez71ePTncZlQ954DfLNMZuOftKZq+2WR+dCXH9QEsf768q9wwd92RXLE=)
#  bucket: pigcloud
#  qiniuHost: http://p0hpm86wj.bkt.clouddn.com/
